services:
  signalbot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SIGNAL_CLI_VERSION: ${SIGNAL_CLI_VERSION}
    working_dir: /app
    volumes:
      - signal-data:/root/.local/share/signal-cli
    environment:
      - AI_PREFIX=${AI_PREFIX}
      - AGENT_URL=${AGENT_URL}
    env_file:
      - ./bot/.env
    command: ['/app/signalbot']

volumes:
  signal-data:
